export const WEB_CONTENT_TYPE_OPTIONS = [
  "Homepage",
  "About Us Page",
  "Treatment Page",
  "Condition Page",
  "Service Page",
  "Department Page",
  "Location Page",
  "Doctor Profile Page",
  "Team Page",
  "Patient Information Page",
  "Blog Page",
  "Guide Page",
  "FAQ Page",
  "Case Study",
  "Press Release",
  "Contact Page",
  "Book Appointment Page",
  "Consultation Page",
  "Second Opinion Page",
  "Pricing Page",
  "Landing Page",
  "Feedback Page",
  "Privacy Policy",
  "Terms and Conditions",
  "Cookie Policy",
  "Medical Disclaimer",
  "404 Page",
] as const;

export type WebContentType = (typeof WEB_CONTENT_TYPE_OPTIONS)[number];
